### PR TITLE
Add compatibility for distributions where /bin/bash does not exist

### PR DESCRIPTION
**Pull request by ghost**
Hard-coding the path of the `bash` binary to `#!/bin/bash` brakes compatibility for distributions where `bash` is not located under `/bin`. To fix this the shebang should be changed to `#!/usr/bin/env bash`.

### CODE REVIEW

**Comment by nils-wisiol** [comment]
Thanks! Please change your commit message:

1. please indicate that your changes are MIT licensed 
2. please prefix the commit message with `fix():` and honor GitHub's 72 char limit for the first line of your commit message

Thanks for contributing!

**Comment by ghost** [comment]
How should I indicate that my changes are MIT licensed?

**Comment by nils-wisiol** [comment]
Maybe just add a second line in your commit message that says "Licensed under MIT" or so. I guess for this particular PR, it's not actually important.

**Comment by ghost** [comment]
I think you can merge it now.

**Comment by nils-wisiol** [comment]
Thanks a lot! @BenKerry

**Pull request merged**
